### ISSUE TITLE
Inconsistent event naming

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/iptools-jquery-offcanvas#1]
Open event is called 'opened' when triggered and 'open' within destroy method. I would suggest to rename the triggered event into 'open' to have it consistent with 'close'. A 'opened' or 'closed' event could be triggered additionally when the animation has completed.

**Comment by davleh** [comment]
Ok, as discussed, only a closed event has to be added, everything else is perfect. :)

**Comment by GeorgMeyer23** [comment]
9fc51fb
