### ISSUE TITLE
How to make a closing a sliding div when you click outside of it?

### ISSUE THREAD

**Issue by zuber143** [interactive-pioneers/iptools-jquery-offcanvas#10]
hi im using this plugin . .i want to "How to make a closing a sliding div when you click outside of it?"

**Comment by GeorgMeyer23** [comment]
Version 1.0.0 will be released soon including an optional 'click outside to close' parameter.

**Comment by GeorgMeyer23** [comment]
@zuber143 you may update to v1.0.1 that includes a documented option 'closeOnClickOutside'
