### ISSUE TITLE
Inconvenient class naming / add option for specifying custom trigger classes

### ISSUE THREAD

**Issue by davleh** [interactive-pioneers/iptools-jquery-offcanvas#2]
Classes are currently statically defined in the plugin, the BEM naming is used. As triggers (open / close) can lie outside the off-canvas container, the BEM naming (especially "offcanvas__trigger--open") does not make sense. I would define a not-styling-related class as trigger, e.g. "js-offcanvas-open" and "js-offcanvas-close" as default. I would also suggest to add plugin options to customize the trigger class names.

**Comment by ain** [comment]
The decision to go BEM was done long ago over many constructive reasons. Only for consistency with other plugins it makes sense to keep it not discussing structural semantics or OOCSS it brings. Also, `js` prefix does not rule out BEM, we've used it alongside for some time now.

**Comment by beroes** [comment]
We should have them both BEM and JS prefixed calsses on the element. BEM is used for styling purposes while JS has pure functional meaning. But I am agree with @davleh  that inside the javascript plugin is better to use JS prefixed classes.

**Comment by davleh** [comment]
I totally agree, generally we should stick with BEM. I'm a big fan of this concept in CSS. But in this special case, triggers can be also used outside the actual offcanvas container. So BEM does not make sense here. Also separating functionality and styling would be an argument for using ".js-offcanvas-open" as trigger. For applying styling rules to the trigger surely BEM should be used!

**Comment by ain** [comment]
Nothing wrong with using long BEM names on top of `js`. Structural info in those `js` selectors provides value to script readability. 

Also, the js selectors would in best case be passed in as `settings.selectors` object for instance, but this is already a separate topic.

**Comment by GeorgMeyer23** [comment]
@ain @davleh @beroes Currently the relation from button to off canvas is determined via data attribute. What about to extend that data attribute to recognise if we're dealing with an open / close button. This would make the classes `offcanvas__trigger--open` and `offcanvas__trigger--close` obsolete and will simplify the structure.

**Comment by ain** [comment]
@GeorgMeyer23 I'm for it. Internally the component can use whatever the class is, by convention. But data attribute is usually more readable and straightforward. It's meant to deliver data and in this case it would.

**Comment by davleh** [comment]
I also like this idea.

**Comment by GeorgMeyer23** [comment]
97c1e553626a5e03c0dfaf11d7dda468786c4adb
