### ISSUE TITLE
Problem with Edge browser

### ISSUE THREAD

**Issue by arturaslt** [interactive-pioneers/iptools-jquery-offcanvas#3]
Does not work on Edge browser
the menu does not appear 
While it works on every other browser

**Comment by ain** [comment]
@GeorgMeyer23 could you see if you can reproduce this on Edge?

**Comment by GeorgMeyer23** [comment]
@arturaslt @ain Tested on Windows 10, Edge 25.10586.0.0 / EdgeHTML 13.10586. Works fine. @arturaslt Can you provide a more detailed bug report or a link with your implementation?

**Comment by arturaslt** [comment]
I'm sorry I also fixed it on the browser,
the problem was that the class to open the menu was an image not a button or a div
sorry for the troubles

**Comment by ain** [comment]
@arturaslt glad it worked out! Feel free to send us feature requests and, even better, Pull Requests!
