### ISSUE TITLE
Evaluate external how-to article for example use-case

### ISSUE THREAD

**Issue by ain** [interactive-pioneers/iptools-jquery-offcanvas#4]
Calling for evaluation. Would it be useful to link to [Minimal Overlaying Off-canvas Plugin With jQuery - Iptools Offcanvas](http://www.jqueryscript.net/menu/Minimal-Overlaying-Off-canvas-Plugin-With-jQuery-Iptools-Offcanvas.html) article in README as for example use-case?

**Comment by GeorgMeyer23** [comment]
Yup, will do so until we provide own examples.

**Comment by Friedrich-Mocker** [comment]
We can close this Issue, right?
By the Way, who wrote the article?

**Comment by ain** [comment]
Yes, we can close it.

Article was by 3rd party we had nothing to do with. Someone just wrote about it :)
