### ISSUE TITLE
Remove static width/height (360px)

### ISSUE THREAD

**Issue by GeorgMeyer23** [interactive-pioneers/iptools-jquery-offcanvas#7]
- use transform translate 100% to toggle visibility.
- example: http://codepen.io/georgmeyer/pen/KzeVzZ

**Comment by Friedrich-Mocker** [comment]
if we use translate 100% it doesnt change anthing concerning functionality. we still cant use calc() on the variable, because its later used with var \* -1, which doesnt work with calc. do you still want me to change it to 100% ?
